### ISSUE TITLE
data & model unavailable for download

### ISSUE THREAD

**Issue by maque-hub** [paulguerrero/pcpnet#10]
when I tried to download the data and pre-trained model the following error occurred:

> You don't have permission to access /group_website/projects/2018/pcpnet/pclouds.zip on this server.
 Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Is it caused by my server or something else? I wonder if anyone has access to the data or the site.

**Comment by paulguerrero** [comment]
Sorry, we are having issues with a server migration, we are working on fixing them right now.

**Comment by paulguerrero** [comment]
The download links should work again now.

**Comment by maque-hub** [comment]
> 
> 
> The download links should work again now.

thanks!
