### ISSUE TITLE
Could anyone share the ground truth generation steps?

### ISSUE THREAD

**Issue by ivchgr01** [paulguerrero/pcpnet#11]
Can anyone share the details steps how we could generate the ground truth normal from point cloud?
I have referred to the previous issue #5, but I don't think I know the exact step to do it. 
I have tried to use CloudCompare to calculate the normal, but it doesn't look right.

**Comment by paulguerrero** [comment]
Hi Ivan, we compute the ground truth normals from the mesh that the points were sampled from, not directly from the point cloud. The original meshes we used to compute the normals are available here:
https://drive.google.com/file/d/14UncfzTN2FgZB_A5NMkAF6aOv_JKDGoR/view?usp=sharing

**Comment by ivchgr01** [comment]
![image](https://user-images.githubusercontent.com/40304114/140856949-074a8c02-b922-46db-929b-2eb9ca0ee382.png)
Thanks for reply!
I am processing some point cloud data e.g. sphere. Base on what you said, I am trying to convert it to mesh and find their normal by using CloudCompare. Did you use CloudCompare too? Or did you use some other way to do it?

**Comment by paulguerrero** [comment]
Hi Ivan, we started out with a mesh, so we did not have to convert a point cloud to a mesh. Computing the normal from a point cloud is not trivial and is one of the reasons we developed PCPNet. To create our ground truth, we randomly sampled points on the mesh surface and used the normal of the face that contains a point as the point normal.

**Comment by ivchgr01** [comment]
Thanks for reply!

**Comment by ivchgr01** [comment]
> Hi Ivan, we started out with a mesh, so we did not have to convert a point cloud to a mesh. Computing the normal from a point cloud is not trivial and is one of the reasons we developed PCPNet. To create our ground truth, we randomly sampled points on the mesh surface and used the normal of the face that contains a point as the point normal.

Thanks for the reply!
