### ISSUE TITLE
curvature values c1>c2?

### ISSUE THREAD

**Issue by ReneHamburger1993** [paulguerrero/pcpnet#13]
Hi,
maybe I am missing something here, but shouldn't the computed principal curvature values be (an approximation) of max/min value of local curvature and therefore c1>=c2 at each point?
Kind regards
Rene

**Comment by paulguerrero** [comment]
Sorry, I am missing the context here a bit, does this refer to the shape curvatures in the dataset? The principal curvature values may not be ordered in the files, but you should be able to order them after reading them from the file.

**Comment by ReneHamburger1993** [comment]
Hi,
thanks for the quick reply!
Context: Yes, its about shape curvatures. I analysed an polymeric membrane from molecular dynamics and was confused about the unordered curvatures which occured in my output using the pretrained data as well in the test data.
Though knowing that output of values is not ordered solves it for me.
Thanks
Rene
