### ISSUE TITLE
How do I use my one Pointcloud

### ISSUE THREAD

**Issue by manuelsgit** [paulguerrero/pcpnet#14]
I want to see how the Net would estimate my one pointcloud.
I added the pointcloud in the pclouds folder (as .xyz and only containing the x y z coordinates) and wrote it in the dataset file.
Unfortunately the eval_pcpnet.py ends around this line:

        dataset = PointcloudPatchDataset(

What can I do about that?

**Comment by paulguerrero** [comment]
Hi @manuelsgit , the list of shapes in the dataset is defined by a text file containing the file name (without extension) of one point cloud per line. The file name is given relative to the location of the text file.

So if you have one point cloud that would be a text file with a single line.
You pass this text file to the `PointcloudPatchDataset` as second argument.

Hope that helps!

**Comment by manuelsgit** [comment]
Thanks a lot! i also changed the input so that the range of the points is between 0 and 1 and now it works :)
