### ISSUE TITLE
If I have the normal, which pre-trained models should I use to obtain the oriented normal?

### ISSUE THREAD

**Issue by linlinge** [paulguerrero/pcpnet#15]
Hello!  I want to use the pre-trained models to obtain a consistent normal orientation for a point cloud that already has the estimated normals. Which pre-trained model should I use?

**Comment by paulguerrero** [comment]
Hi Linlin,
the pre-trained models do not support this, they only support estimating normals/curvature directly from point clouds (so without unoriented normals as input). You could alter the code a bit to accept 6-dimensional point inputs (xyz, unoriented normal) and train this updated model to predict the oriented normal. Although there are also methods more specialized in your problem like this one:
https://cims.nyu.edu/gcl/papers/2021-Dipole.pdf

Hope that helps!
