### ISSUE TITLE
For dressing

### ISSUE THREAD

**Issue by MulinYu** [paulguerrero/pcpnet#3]
Hello,
Thank u for ur sharing.

I want to know how do you dressing the 3D images which have different color in different place with different properties.

best,
mulin

**Comment by paulguerrero** [comment]
Hi Mulin,
to handle points with rgb color values, you could, for example, multiply the the n-dimensional features vectors just before the sum with the colors to get 3n-dimensional feature vectors (then the point functions would act as continuous kernel functions over 3d space), or you could augment the position of the points with the color values to get 6-dimensional input points.

hope that helps,
Paul

**Comment by MulinYu** [comment]
Thanks a lot.
best
