### ISSUE TITLE
For multi_scale

### ISSUE THREAD

**Issue by MulinYu** [paulguerrero/pcpnet#4]
Hello,
Thanks for ur reponse and sharing.

I noticed that you mentioned in the paper that you translated the patch to the origin and normalize its radius multiplying with 1/r.  And you transform output curvatures to the original scale of the point cloud by multiplying with r. But in case of multi_scale, there are more than one r. How do you transform the output curvatures to the original scale?

Have a good day,

best,
mulin

**Comment by paulguerrero** [comment]
Hi Mulin, since there is a constant relationship between the patch sizes, the network can learn to adjust the scale itself when it combines the information from the multi-scale patches.
