### ISSUE TITLE
Ground truth normal generation

### ISSUE THREAD

**Issue by ziruiw-dev** [paulguerrero/pcpnet#5]
Hi @paulguerrero,

Thanks for releasing your code. I was wondering if I can ask how are the ground truth normals generated in the dataset? Is it using PCA and KNN?

Best,
Zirui

**Comment by paulguerrero** [comment]
Hi Zirui,
all point clouds were sampled from dense ground truth meshes, and the ground truth normals are obtained from these meshes (the normal of the face containing a point).

**Comment by ziruiw-dev** [comment]
Thanks a lot for the prompt response and answer. Best, Zirui
