### ISSUE TITLE
Generate the mesh or pointcloud 

### ISSUE THREAD

**Issue by belal-ibrahim** [paulguerrero/pcpnet#7]
I have trained my data and i got the normals and curvatures files,but i don't know how to generate the mesh or texture scene! any recommendations?

**Comment by paulguerrero** [comment]
In the paper we used Poisson reconstruction with the generated normals to reconstruct a surface, more specifically we used the implementation on this webpage:
http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version13.00/

But there is also a CGAL implementation if you prefer:
https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html

Hope that helps!

**Comment by belal-ibrahim** [comment]
Thanks it's really helpful

**Comment by ivchgr01** [comment]
Would you mind to share the details steps how we could generate the ground truth normal from point cloud?
I have tried to use CloudCompare to calculate the normal, but it doesn't look right.
