### ISSUE TITLE
Can I generate point cloud and normals from stl file?

### ISSUE THREAD

**Issue by DeanLee18** [paulguerrero/pcpnet#8]
I'm trying to generate point cloud data from mesh such as .stl file, but I failed to create the groundtrue normals of sampled points. Is there any way to generate point cloud and normals from stl file using 3D tools like MeshLab? Thanks.

**Comment by paulguerrero** [comment]
Yes, in MeshLab you can do Poisson disk sampling, for example (Filters > Sampling > Poisson-disk Sampling), which also generates normals for the points.

**Comment by DeanLee18** [comment]
Thanks! May I ask for some advice on how to sample point cloud non-uniformly, just as you show in the paper PCPNet?

**Comment by paulguerrero** [comment]
This is probably not available in editor like MeshLab. One way to do this is to first make sure that your mesh only has small triangles (remesh it if necessary), and when placing point samples, pick triangles with a probability proportional to their normalized (area * density the points should have on the triangle). For example, if there should be a density gradient from top to bottom, triangles on top should have a higher probability of being picked. Inside the triangle, you can sample uniformly. This should be a good enough approximation if the triangles are small enough.

**Comment by pratulyab** [comment]
@paulguerrero can you share the original 3D shapes and figurines from which the point clouds were sampled? 
Also did you use triangular meshes?

**Comment by paulguerrero** [comment]
Here is a link to the original 3D meshes:
https://drive.google.com/file/d/14UncfzTN2FgZB_A5NMkAF6aOv_JKDGoR/view?usp=sharing
